version: '3.8'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=name
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=biblio
    ports:
      - '5432:5432'
    volumes: 
      - data:/var/lib/postgresql/data
      - data:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 1s
    #   timeout: 3s
    #   retries: 30

  # api:
  #   container_name: api
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8082:8082
  #   volumes:
  #     - ./api:/app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin4_container
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: azerty
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin

volumes:
  data:
    driver: local